create table app_users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone,
  email varchar(255),
  nickname varchar(255),
  platform_admin boolean not null,
  provider varchar(255),
  provider_user_id varchar(255),
  password_hash varchar(255),
  active_session_id varchar(255),
  locked_until timestamp with time zone,
  failed_login_attempts integer,
  constraint uk_app_users_email unique (email)
);

create table family_groups (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone,
  name varchar(255)
);

create table family_members (
  id bigint generated by default as identity primary key,
  can_create boolean not null,
  can_delete boolean not null,
  can_read boolean not null,
  can_update boolean not null,
  family_id bigint,
  joined_at timestamp with time zone,
  role varchar(255),
  user_id bigint
);

create table family_schedules (
  id bigint generated by default as identity primary key,
  calendar_basis varchar(255),
  category varchar(255),
  created_at timestamp with time zone,
  family_id bigint,
  member_name varchar(255),
  memo varchar(255),
  repeat_rule varchar(255),
  schedule_date date,
  schedule_time time without time zone,
  title varchar(255)
);

create table app_notifications (
  id bigint generated by default as identity primary key,
  body varchar(255),
  created_at timestamp with time zone,
  family_id bigint,
  read_at timestamp with time zone,
  schedule_id bigint,
  target_date date,
  title varchar(255),
  type varchar(255),
  user_id bigint,
  constraint uk_app_notifications_schedule_user unique (user_id, schedule_id, type, target_date)
);

create table ledger_entries (
  id bigint generated by default as identity primary key,
  amount numeric(38,2),
  category varchar(255),
  created_at timestamp with time zone,
  entry_type varchar(255),
  family_id bigint,
  member_name varchar(255),
  memo varchar(255),
  payment_method varchar(255),
  title varchar(255),
  transaction_date date
);

create table trips (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone,
  description varchar(255),
  end_date date,
  family_id bigint,
  start_date date,
  title varchar(255)
);

create table travel_records (
  id bigint generated by default as identity primary key,
  amount numeric(38,2),
  category varchar(255),
  created_at timestamp with time zone,
  latitude double precision,
  location varchar(255),
  longitude double precision,
  note varchar(255),
  record_date date,
  record_time time without time zone,
  sort_order integer,
  title varchar(255),
  trip_id bigint
);

create table travel_record_media_urls (
  travel_record_id bigint not null,
  media_urls varchar(255)
);

create table baby_profiles (
  id bigint generated by default as identity primary key,
  birth_date date,
  created_at timestamp with time zone,
  family_id bigint,
  gender varchar(255),
  latest_height_cm numeric(38,2),
  latest_weight_kg numeric(38,2),
  memo varchar(255),
  name varchar(255),
  photo_url varchar(255)
);

create table baby_records (
  id bigint generated by default as identity primary key,
  amount_ml integer,
  baby_id bigint,
  created_at timestamp with time zone,
  height_cm numeric(38,2),
  memo varchar(255),
  record_date date,
  record_time varchar(255),
  record_type varchar(255),
  weight_kg numeric(38,2)
);

create table baby_record_media_urls (
  baby_record_id bigint not null,
  media_urls varchar(255)
);

create table family_diaries (
  id bigint generated by default as identity primary key,
  body varchar(255),
  created_at timestamp with time zone,
  diary_date date,
  family_id bigint,
  max_temperature integer,
  min_temperature integer,
  mood varchar(255),
  title varchar(255),
  weather varchar(255)
);

create table family_diary_media_urls (
  family_diary_id bigint not null,
  media_urls varchar(255)
);

create table common_code_groups (
  id bigint generated by default as identity primary key,
  active boolean not null,
  code varchar(255),
  created_at timestamp with time zone,
  family_id bigint,
  menu_key varchar(255),
  name varchar(255)
);

create table common_codes (
  id bigint generated by default as identity primary key,
  active boolean not null,
  code varchar(255),
  created_at timestamp with time zone,
  group_id bigint,
  name varchar(255),
  sort_order integer
);

create table community_posts (
  id bigint generated by default as identity primary key,
  author_id bigint,
  author_name varchar(255),
  board_type varchar(255),
  body oid,
  created_at timestamp with time zone,
  family_id bigint,
  title varchar(255),
  updated_at timestamp with time zone
);

create table community_post_media_urls (
  community_post_id bigint not null,
  media_urls varchar(255)
);

create table community_comments (
  id bigint generated by default as identity primary key,
  author_id bigint,
  author_name varchar(255),
  body oid,
  created_at timestamp with time zone,
  post_id bigint,
  updated_at timestamp with time zone
);

create index idx_family_members_user on family_members (user_id);
create index idx_family_members_family on family_members (family_id);
create index idx_family_schedules_family_date on family_schedules (family_id, schedule_date);
create index idx_ledger_entries_family_date on ledger_entries (family_id, transaction_date);
create index idx_trips_family on trips (family_id);
create index idx_travel_records_trip_order on travel_records (trip_id, sort_order);
create index idx_baby_profiles_family on baby_profiles (family_id);
create index idx_baby_records_baby_date on baby_records (baby_id, record_date);
create index idx_family_diaries_family_date on family_diaries (family_id, diary_date);
create index idx_common_code_groups_family_menu on common_code_groups (family_id, menu_key);
create index idx_common_codes_group_order on common_codes (group_id, sort_order);
create index idx_community_posts_board_created on community_posts (board_type, created_at);
create index idx_community_comments_post_created on community_comments (post_id, created_at);
create index idx_app_notifications_user_created on app_notifications (user_id, created_at);
